eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
 #okta:
  #oauth2:
    #issuer: https://dev-39508552.okta.com/oauth2/default
    #audience: api://default
 #spring:
  #cloud:
    #config:
      #enabled: true
      #uri:
        #- http://localhost:9296
      #label: master
spring:
  zipkin:
    baseUrl: http://zipkin-svc:9411
